/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTag: typeof import('element-plus/es')['ElTag']
    FilterManager: typeof import('./components/filters/FilterManager.vue')['default']
    FilterTag: typeof import('./components/filters/FilterTag.vue')['default']
    Item: typeof import('./components/Item.vue')['default']
    PageHeader: typeof import('./components/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./components/filters/Select.vue')['default']
    SpellList: typeof import('./components/SpellList.vue')['default']
    Spells: typeof import('./components/Spells.vue')['default']
  }
}
