/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BookmarkButton: typeof import('./components/BookmarkButton.vue')['default']
    BookmarkManager: typeof import('./components/BookmarkManager.vue')['default']
    ButtonFilter: typeof import('./components/filters/ButtonFilter.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckboxButton: typeof import('element-plus/es')['ElCheckboxButton']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FilterManager: typeof import('./components/filters/FilterManager.vue')['default']
    FilterTag: typeof import('./components/filters/FilterTag.vue')['default']
    IMaterialSymbolsLightDeleteOutline: typeof import('~icons/material-symbols-light/delete-outline')['default']
    IMaterialSymbolsLightVisibility: typeof import('~icons/material-symbols-light/visibility')['default']
    IMaterialSymbolsLightVisibilityOff: typeof import('~icons/material-symbols-light/visibility-off')['default']
    IMslAdd2: typeof import('~icons/material-symbols-light/add2')['default']
    IMslBookmarkOutlineSharp: typeof import('~icons/material-symbols-light/bookmark-outline-sharp')['default']
    IMslBookmarkSharp: typeof import('~icons/material-symbols-light/bookmark-sharp')['default']
    IMslLabelOffOutline: typeof import('~icons/material-symbols-light/label-off-outline')['default']
    IMslPrintOutline: typeof import('~icons/material-symbols-light/print-outline')['default']
    IMslStarRounded: typeof import('~icons/material-symbols-light/star-rounded')['default']
    ListPage: typeof import('./components/ListPage.vue')['default']
    PageHeader: typeof import('./components/PageHeader.vue')['default']
    PrintCard: typeof import('./components/PrintCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/filters/Search.vue')['default']
    Select: typeof import('./components/filters/Select.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
