/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bookmarks': RouteRecordInfo<
      '/bookmarks',
      '/bookmarks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/print': RouteRecordInfo<
      '/print',
      '/print',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/search/[topic]': RouteRecordInfo<
      '/search/[topic]',
      '/search/:topic',
      { topic: ParamValue<true> },
      { topic: ParamValue<false> },
      | never
    >,
    '/view/[bookmarkList]': RouteRecordInfo<
      '/view/[bookmarkList]',
      '/view/:bookmarkList',
      { bookmarkList: ParamValue<true> },
      { bookmarkList: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.md': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/bookmarks.vue': {
      routes:
        | '/bookmarks'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/print.vue': {
      routes:
        | '/print'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/search/[topic].vue': {
      routes:
        | '/search/[topic]'
      views:
        | never
      pathParamNames:
        | 'topic'
    }
    'src/pages/view/[bookmarkList].vue': {
      routes:
        | '/view/[bookmarkList]'
      views:
        | never
      pathParamNames:
        | 'bookmarkList'
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
